import type { Metadata } from "next";
import { Inter, Volkhov } from "next/font/google";
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Specify the weights you need
  variable: "--font-inter", // Use CSS variable for Poppins
});

const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights for Volkhov
  variable: "--font-volkhov", // Use CSS variable for Volkhov
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${volkhov.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
